#!/bin/bash
#定义变量

#NAME=
#循环拼写
for TMP in `cat $1`
do
	SYNC_NAME=`echo $TMP|awk -F"." '{print $2}'|awk 'gsub(/^ *| *$/,"")'`
	TAB_NAME=`echo $TMP|awk 'gsub(/^ *| *$/,"")'`


echo '<SyncLet name="'${SYNC_NAME}'" >'
echo '       <MonitorTable>'${TAB_NAME}'</MonitorTable>'
echo '       <Method>'
echo '            <Filter>'
echo '<![CDATA['
echo '      %j$TIMESTAMP%.substring(9,10).equals("1") && ! %j$TIMESTAMP%.substring(8,9).equals("3")'
echo ']]>'
echo '            </Filter>'
echo '            <ApplyInsertOnFailUpdate/>'
echo '            <TargetTable jdbc="jdbc_rp">'
echo '                '${TAB_NAME}'_01'
echo '            </TargetTable>'
echo '            <ColumnMapping>'
echo '                <Mapping from="j$TIMESTAMP" to="ODSTIME"/>'
echo '            </ColumnMapping>'
echo '       </Method>'
echo '	   '
echo '	   <Method>'
echo '            <Filter>'
echo '<![CDATA['
echo '      %j$TIMESTAMP%.substring(9,10).equals("2") '
echo ']]>'
echo '            </Filter>'
echo '            <ApplyInsertOnFailUpdate/>'
echo '            <TargetTable jdbc="jdbc_rp">'
echo '                '${TAB_NAME}'_02'
echo '            </TargetTable>'
echo '            <ColumnMapping>'
echo '                <Mapping from="j$TIMESTAMP" to="ODSTIME"/>'
echo '            </ColumnMapping>'
echo '       </Method>'
echo '	   '
echo '	   <Method>'
echo '            <Filter>'
echo '<![CDATA['
echo '      %j$TIMESTAMP%.substring(9,10).equals("3") '
echo ']]>'
echo '            </Filter>'
echo '            <ApplyInsertOnFailUpdate/>'
echo '            <TargetTable jdbc="jdbc_rp">'
echo '                '${TAB_NAME}'_03'
echo '            </TargetTable>'
echo '            <ColumnMapping>'
echo '                <Mapping from="j$TIMESTAMP" to="ODSTIME"/>'
echo '            </ColumnMapping>'
echo '       </Method>'
echo '	   '
echo '	   <Method>'
echo '            <Filter>'
echo '<![CDATA['
echo '      %j$TIMESTAMP%.substring(9,10).equals("4") '
echo ']]>'
echo '            </Filter>'
echo '            <ApplyInsertOnFailUpdate/>'
echo '            <TargetTable jdbc="jdbc_rp">'
echo '                '${TAB_NAME}'_04'
echo '            </TargetTable>'
echo '            <ColumnMapping>'
echo '                <Mapping from="j$TIMESTAMP" to="ODSTIME"/>'
echo '            </ColumnMapping>'
echo '       </Method>'
echo '	   '
echo '	   <Method>'
echo '            <Filter>'
echo '<![CDATA['
echo '      %j$TIMESTAMP%.substring(9,10).equals("5") '
echo ']]>'
echo '            </Filter>'
echo '            <ApplyInsertOnFailUpdate/>'
echo '            <TargetTable jdbc="jdbc_rp">'
echo '                '${TAB_NAME}'_05'
echo '            </TargetTable>'
echo '            <ColumnMapping>'
echo '                <Mapping from="j$TIMESTAMP" to="ODSTIME"/>'
echo '            </ColumnMapping>'
echo '       </Method>'
echo '	   '
echo '	   <Method>'
echo '            <Filter>'
echo '<![CDATA['
echo '      %j$TIMESTAMP%.substring(9,10).equals("6") '
echo ']]>'
echo '            </Filter>'
echo '            <ApplyInsertOnFailUpdate/>'
echo '            <TargetTable jdbc="jdbc_rp">'
echo '                '${TAB_NAME}'_06'
echo '            </TargetTable>'
echo '            <ColumnMapping>'
echo '                <Mapping from="j$TIMESTAMP" to="ODSTIME"/>'
echo '            </ColumnMapping>'
echo '       </Method>'
echo '	   '
echo '	   <Method>'
echo '            <Filter>'
echo '<![CDATA['
echo '      %j$TIMESTAMP%.substring(9,10).equals("7") '
echo ']]>'
echo '            </Filter>'
echo '            <ApplyInsertOnFailUpdate/>'
echo '            <TargetTable jdbc="jdbc_rp">'
echo '                '${TAB_NAME}'_07'
echo '            </TargetTable>'
echo '            <ColumnMapping>'
echo '                <Mapping from="j$TIMESTAMP" to="ODSTIME"/>'
echo '            </ColumnMapping>'
echo '       </Method>'
echo '	   '
echo '	   <Method>'
echo '            <Filter>'
echo '<![CDATA['
echo '      %j$TIMESTAMP%.substring(9,10).equals("8") '
echo ']]>'
echo '            </Filter>'
echo '            <ApplyInsertOnFailUpdate/>'
echo '            <TargetTable jdbc="jdbc_rp">'
echo '                '${TAB_NAME}'_08'
echo '            </TargetTable>'
echo '            <ColumnMapping>'
echo '                <Mapping from="j$TIMESTAMP" to="ODSTIME"/>'
echo '            </ColumnMapping>'
echo '       </Method>'
echo '	   '
echo '	   <Method>'
echo '            <Filter>'
echo '<![CDATA['
echo '      %j$TIMESTAMP%.substring(9,10).equals("9") '
echo ']]>'
echo '            </Filter>'
echo '            <ApplyInsertOnFailUpdate/>'
echo '            <TargetTable jdbc="jdbc_rp">'
echo '                '${TAB_NAME}'_09'
echo '            </TargetTable>'
echo '            <ColumnMapping>'
echo '                <Mapping from="j$TIMESTAMP" to="ODSTIME"/>'
echo '            </ColumnMapping>'
echo '       </Method>'
echo '	   '
echo '	   <Method>'
echo '            <Filter>'
echo '<![CDATA['
echo '      %j$TIMESTAMP%.substring(9,10).equals("0") '
echo ']]>'
echo '            </Filter>'
echo '            <ApplyInsertOnFailUpdate/>'
echo '            <TargetTable jdbc="jdbc_rp">'
echo '                '${TAB_NAME}'_10'
echo '            </TargetTable>'
echo '            <ColumnMapping>'
echo '                <Mapping from="j$TIMESTAMP" to="ODSTIME"/>'
echo '            </ColumnMapping>'
echo '       </Method>'
echo '	   '
echo '	   <Method>'
echo '            <Filter>'
echo '<![CDATA['
echo '      %j$TIMESTAMP%.substring(9,10).equals("1") && %j$TIMESTAMP%.substring(8,9).equals("3")'
echo ']]>'
echo '            </Filter>'
echo '            <ApplyInsertOnFailUpdate/>'
echo '            <TargetTable jdbc="jdbc_rp">'
echo '                '${TAB_NAME}'_31'
echo '            </TargetTable>'
echo '            <ColumnMapping>'
echo '                <Mapping from="j$TIMESTAMP" to="ODSTIME"/>'
echo '            </ColumnMapping>'
echo '       </Method>'
echo '	   '
echo '	   <Method>'
echo '            <TargetTable jdbc="jdbc_rp">'
echo '                '${TAB_NAME}''
echo '            </TargetTable>'
echo '            <ColumnMapping>'
echo '                <Mapping from="j$TIMESTAMP" to="ODSTIME"/>'
echo '            </ColumnMapping>'
echo '       </Method>'
echo '</SyncLet>'
echo '    '

done
